{
 "title": "Аналитика",
 "tags": [ "analytics" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Средняя длительность сдачи/выдачи в системе",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(job_session_seconds_sum / job_session_seconds_count) / 60"
    }
   ]
  },
  {
   "title": "Полнокомплектных выдач",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(toolkit_completed_total{action=\"TOOLS_ISSUANCE\"} / session_total{action=\"TOOLS_ISSUANCE\"}) * 100"
    }
   ]
  },
  {
   "title": "Полнокомплектных сдач",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(toolkit_completed_total{action=\"TOOLS_RETURN\"} / session_total{action=\"TOOLS_RETURN\"}) * 100"
    }
   ]
  },
  {
   "title": "Средняя уверенность распознавания инструмента",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(app_model_confidence_sum / app_model_confidence_count) * 100"
    }
   ]
  },
  {
   "title": "Среднее время обработки одного изображения",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(image_processing_duration_seconds_sum/image_processing_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "Доля сдач/выдач без жалоб на распознавание",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((scalar(sum(session_total)) - scalar(sum(session_with_reports_total))) / scalar(sum(session_total))) * 100"
    }
   ]
  },
  {
   "title": "Наиболее часто отсутствующие инструменты",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "topk(5, {__name__=\"tool_report_count_total\"})"
    }
   ]
  },
  {
   "title": "Всего проверок",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(session_total)" }
   ]
  }
 ]
}